baseURL: "https://ngmsh.github.io"
title: "ニガムシカミツブス"
lang: "ja"

langageCode: "ja-jp"
defaultContentLanguage: "ja"

canonifyurls: true
publishDir: "docs"
enableEmoji: true
enableInlineShortcodes: true
hasCJKLanguage: true
relativeURLs: true

markup:
  goldmark:
    renderer:
      unsafe: true

theme: hugo-now-ui-custom
# theme: airspace-hugo
# theme: infinity-hugo
# theme: meghna-hugo

params:
  custom_css:
    - "css/style.css"
    - "css/font.css"
  custom_js:
    - "../modules/reveal.js/js/reveal.js"

indexes:
  tag: "tags"
  topic: "topics"

menu:
  main:
    - name: "Home"
      url: "/"
      pre: "<i class='now-ui-icons design_app'></i>"
      weight: 1
    - name: "About"
      url: "/about/"
      pre: "<i class='now-ui-icons design_app'></i>"
      weight: 2
    - name: "Next"
      url: "/next/"
      pre: "<i class='now-ui-icons design_app'></i>"
      weight: 3
    - name: "Reserve"
      url: "/rsv/"
      pre: "<i class='now-ui-icons design_app'></i>"
      weight: 4
  footer:
    - identifier: "twitter"
      pre: "<i class='fa fa-twitter'></i>"
      url: "https://twitter.com/taro_on_stage"
      weight: 1
    - identifier: "github"
      pre: "<i class='fa fa-github'></i>"
      url: "https://github.com/ngmsh"
      weight: 2
