version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8b:16:aa:4e:fc:8c:88:4e:83:2d:38:75:f1:45:56:a4"
      - run:
          name: Build
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            git clone git@github.com:ngmsh/blog
            cd blog
            git submodule sync
            git submodule update --init
            git submodule foreach git pull origin master
            hugo
      - run:
          name: Deploy
          # git remote set-url origin https://github.com/ngmsh/ngmsh.github.io
          command: |
            git clone git@github.com:ngmsh/ngmsh.github.io.git
            cd ngmsh.github.io
            git config --global user.email "crunch.the.nigamushi@gmail.com"
            git config --global user.name "Taro"
            rm -rf *
            cp -r ../blog/docs/* .
            ls -l
            git add .
            git commit -m "publish by circleci"
            git push origin master
workflows:
  version: 2
  release:
      jobs:
        - build:
            filters:
              branches:
                only: master
